services:
  - type: web
    name: video-stream-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: CAMERA_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0